registro-web/src/main/java/com/directv/registro/web/sp/model/Cliente.java
/*
 * Copyright (C) 2016 dacopanCM
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.directv.registro.web.sp.model;

import com.directv.registro.web.exceptions.CustomException;
import com.directv.registro.web.helper.HelperUtil;
import com.directv.registro.web.json.Equipo;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author dacopanCM
 */
@Entity
@Table(name = "cliente")
public class Cliente implements java.io.Serializable {

    private Integer cltId;
    private Plan plan;
    private String cltNombre;
    private String cltApellido;
    private String cltCi;
    private String cltTelefono;
    private String cltEmail;
    private String cltDireccion;
    private String cltContrato;
    private Boolean cltInstalado;
    private String cltProcId;
    private String cltEstado;
    private String cltEquipos;
    private String cltEncuesta;
    private Boolean cltIsPrepago;
    private Set<ListaEsperaInstalacion> listaEsperaInstalacions = new HashSet(0);

    private ArrayList equipos;
    private HashMap<String, String> encuesta;

    public Cliente() {
    }

    public Cliente(Plan plan) {
        this.plan = plan;
    }

    public Cliente(Integer cltId, Plan plan, String cltNombre, String cltApellido, String cltCi, String cltTelefono, String cltEmail, String cltDireccion, String cltContrato, Boolean cltInstalado, String cltProcId, String cltEstado, String cltEquipos, String cltEncuesta, Boolean cltIsPrepago, ArrayList equipos) {
        this.cltId = cltId;
        this.plan = plan;
        this.cltNombre = cltNombre;
        this.cltApellido = cltApellido;
        this.cltCi = cltCi;
        this.cltTelefono = cltTelefono;
        this.cltEmail = cltEmail;
        this.cltDireccion = cltDireccion;
        this.cltContrato = cltContrato;
        this.cltInstalado = cltInstalado;
        this.cltProcId = cltProcId;
        this.cltEstado = cltEstado;
        this.cltEquipos = cltEquipos;
        this.cltEncuesta = cltEncuesta;
        this.cltIsPrepago = cltIsPrepago;
        this.equipos = equipos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "clt_id", unique = true, nullable = false)
    public Integer getCltId() {
        return this.cltId;
    }

    public void setCltId(Integer cltId) {
        this.cltId = cltId;
    }

    @XmlTransient
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pln_id", nullable = false)
    public Plan getPlan() {
        return this.plan;
    }

    public void setPlan(Plan plan) {
        this.plan = plan;
    }

    @Column(name = "clt_nombre", length = 45)
    public String getCltNombre() {
        return this.cltNombre;
    }

    public void setCltNombre(String cltNombre) {
        this.cltNombre = cltNombre;
    }

    @Column(name = "clt_apellido", length = 45)
    public String getCltApellido() {
        return this.cltApellido;
    }

    public void setCltApellido(String cltApellido) {
        this.cltApellido = cltApellido;
    }

    @Column(name = "clt_ci", length = 10)
    public String getCltCi() {
        return this.cltCi;
    }

    public void setCltCi(String cltCi) {
        this.cltCi = cltCi;
    }

    @Column(name = "clt_telefono", length = 10)
    public String getCltTelefono() {
        return this.cltTelefono;
    }

    public void setCltTelefono(String cltTelefono) {
        this.cltTelefono = cltTelefono;
    }

    @Column(name = "clt_email", length = 45)
    public String getCltEmail() {
        return this.cltEmail;
    }

    public void setCltEmail(String cltEmail) {
        this.cltEmail = cltEmail;
    }

    @Column(name = "clt_direccion", length = 80)
    public String getCltDireccion() {
        return this.cltDireccion;
    }

    public void setCltDireccion(String cltDireccion) {
        this.cltDireccion = cltDireccion;
    }

    @Column(name = "clt_contrato", length = 80)
    public String getCltContrato() {
        return this.cltContrato;
    }

    public void setCltContrato(String cltContrato) {
        this.cltContrato = cltContrato;
    }

    @Column(name = "clt_instalado")
    public Boolean getCltInstalado() {
        return this.cltInstalado;
    }

    public void setCltInstalado(Boolean cltInstalado) {
        this.cltInstalado = cltInstalado;
    }

    @Column(name = "clt_proc_id", nullable = false, length = 80)
    public String getCltProcId() {
        return cltProcId;
    }

    public void setCltProcId(String cltProcId) {
        this.cltProcId = cltProcId;
    }

    @Column(name = "clt_estado", nullable = false, length = 45)
    public String getCltEstado() {
        return cltEstado;
    }

    public void setCltEstado(String cltEstado) {
        this.cltEstado = cltEstado;
    }

    @Column(name = "clt_is_prepago")
    public Boolean getCltIsPrepago() {
        return cltIsPrepago;
    }

    public void setCltIsPrepago(Boolean cltIsPrepago) {
        this.cltIsPrepago = cltIsPrepago;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente",cascade = CascadeType.ALL)
    @XmlTransient
    public Set<ListaEsperaInstalacion> getListaEsperaInstalacions() {
        return this.listaEsperaInstalacions;
    }

    public void setListaEsperaInstalacions(Set<ListaEsperaInstalacion> listaEsperaInstalacions) {
        this.listaEsperaInstalacions = listaEsperaInstalacions;
    }

    @Column(name = "clt_equipos", nullable = true, length = 65535)
    public String getCltEquipos() {
        return cltEquipos;
    }

    public void setCltEquipos(String cltEquipos) {
        this.cltEquipos = cltEquipos;
    }

    @Column(name = "clt_encuesta", nullable = true, length = 65535)
    public String getCltEncuesta() {
        return cltEncuesta;
    }

    public void setCltEncuesta(String cltEncuesta) {
        this.cltEncuesta = cltEncuesta;
    }

    @Transient
    public ArrayList<Equipo> getEquipos() {
        if (equipos == null) {
            if (cltEquipos != null && !cltEquipos.trim().isEmpty()) {
                try {
                    equipos = HelperUtil.fromJSON(cltEquipos, new TypeReference<ArrayList<Equipo>>() {
                    });

                } catch (CustomException ex) {

                }
            }
        }
        return equipos;
    }

    @Transient
    public HashMap<String, String> getEncuesta() {
        if (encuesta == null) {
            if (cltEncuesta != null && !cltEncuesta.trim().isEmpty()) {
                try {
                    encuesta = HelperUtil.fromJSON(cltEncuesta, new TypeReference<HashMap<String, String>>() {
                    });

                } catch (CustomException ex) {

                }
            }
        }
        return encuesta;
    }

    //custom
    @Transient
    public String getFullName() {
        return new StringBuilder().append(cltApellido).append(" ").append(cltNombre).toString();
    }

}

registro-web/src/main/java/com/directv/registro/web/sp/model/ListaEsperaInstalacion.java
package com.directv.registro.web.sp.model;
// Generated 16/07/2016 6:36:03 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ListaEsperaInstalacion generated by hbm2java
 */
@Entity
@Table(name = "lista_espera_instalacion")
public class ListaEsperaInstalacion implements java.io.Serializable {

    private Integer lstInsId;
    private Cliente cliente;
    private Date lstInsFechaIn;
    private Date lstInsFechaOut;

    public ListaEsperaInstalacion() {
    }

    public ListaEsperaInstalacion(Cliente cliente) {
        this.cliente = cliente;
    }

    public ListaEsperaInstalacion(Cliente cliente, Date lstInsFechaIn) {
        this.cliente = cliente;
        this.lstInsFechaIn = lstInsFechaIn;
    }

    public ListaEsperaInstalacion(Cliente cliente, Date lstInsFechaIn, Date lstInsFechaOut) {
        this.cliente = cliente;
        this.lstInsFechaIn = lstInsFechaIn;
        this.lstInsFechaOut = lstInsFechaOut;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "lst_ins_id", unique = true, nullable = false)
    public Integer getLstInsId() {
        return this.lstInsId;
    }

    public void setLstInsId(Integer lstInsId) {
        this.lstInsId = lstInsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "clt_id", nullable = false)
    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lst_ins_fecha_in", length = 19)
    public Date getLstInsFechaIn() {
        return this.lstInsFechaIn;
    }

    public void setLstInsFechaIn(Date lstInsFechaIn) {
        this.lstInsFechaIn = lstInsFechaIn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lst_ins_fecha_out", length = 19)
    public Date getLstInsFechaOut() {
        return this.lstInsFechaOut;
    }

    public void setLstInsFechaOut(Date lstInsFechaOut) {
        this.lstInsFechaOut = lstInsFechaOut;
    }

}

registro-web/src/main/java/com/directv/registro/web/managedBean/AdminClientesBean.java
/*
 * Copyright (C) 2016 dacopanCM
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.directv.registro.web.managedBean;

import com.directv.registro.web.exceptions.CustomException;
import com.directv.registro.web.sp.model.Cliente;
import com.directv.registro.web.sp.service.ClienteService;
import com.directv.registro.web.sp.service.JbpmService;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.primefaces.event.FileUploadEvent;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.util.UriUtils;

/**
 *
 * @author dacopanCM
 */
@ManagedBean(name = "adminClientesBean")
@ViewScoped
public class AdminClientesBean implements Serializable {

    private final Log log = LogFactory.getLog(getClass());

    @ManagedProperty(value = "#{ClienteService}")
    private ClienteService clienteService;

    @ManagedProperty(value = "#{JbpmService}")
    private JbpmService jbpmService;

    private List<Cliente> listCliente;
    private Cliente selectedCliente;

    public AdminClientesBean() {
    }

    @PostConstruct
    public void postConstruct() {

    }

    public void resetAddCliente(ActionEvent actionEvent) {
        selectedCliente = new Cliente();

    }

    public void handleFileUpload(FileUploadEvent event) {

        try {
            clienteService.uploadContrato(selectedCliente, event.getFile());
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Succesful", event.getFile().getFileName() + " is uploaded."));
            listCliente = null;
        } catch (CustomException ex) {
            log.error("error al guardar pdf", ex);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Error", "Error al guardar pdf"));
        } catch (Exception ex) {
            log.error("error desconocido al guardar pdf", ex);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Error", "Error al guardar pdf"));

        }

    }

    public String viewClienteRequestPageAction() {
        try {
            return "/views/s/viewCliente.xhtml?faces-redirect=true&cltId=" + selectedCliente.getCltId() + "&h=" + UriUtils.encode(new BCryptPasswordEncoder().encode(selectedCliente.getCltId().toString()), "UTF-8")
                    + "&r=adminClientes";
        } catch (UnsupportedEncodingException ex) {
            log.error("jom: " + ex, ex);
        }
        return null;
    }

    //get set
    public ClienteService getClienteService() {
        return clienteService;
    }

    public void setClienteService(ClienteService clienteService) {
        this.clienteService = clienteService;
    }

    //props
    public List<Cliente> getListCliente() {
        if (listCliente == null) {
            listCliente = clienteService.getAllCliente();
        }
        return listCliente;
    }

    public void setListCliente(List<Cliente> listCliente) {
        this.listCliente = listCliente;
    }

    public Cliente getSelectedCliente() {
        return selectedCliente;
    }

    public void setSelectedCliente(Cliente selectedCliente) {
        this.selectedCliente = selectedCliente;
    }

    public JbpmService getJbpmService() {
        return jbpmService;
    }

    public void setJbpmService(JbpmService jbpmService) {
        this.jbpmService = jbpmService;
    }
}

registro-web/src/main/java/com/directv/registro/web/managedBean/EstadisticasBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.directv.registro.web.managedBean;

import com.directv.registro.web.helper.HelperUtil;
import com.directv.registro.web.sp.service.JbpmService;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author dacopan
 */
@ManagedBean(name = "estadisticasBean")
@ViewScoped
public class EstadisticasBean implements Serializable {

    private final Log log = LogFactory.getLog(HelperUtil.class);

    @ManagedProperty(value = "#{JbpmService}")
    private JbpmService jbpmService;

    public EstadisticasBean() {
    }

    @PostConstruct
    public void postConstruct() {
    }

    public String getMemory() {
        return HelperUtil.getMemoryUse();

    }

    public void clearJbpmLog(ActionEvent actionEvent) {
        try {
            jbpmService.clearJbpmLog();
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Succesful", "Logs eliminados."));
        } catch (Exception ex) {
            log.error("clear lbpm", ex);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Error", "Logs no eliminados."));
        }
    }

    public JbpmService getJbpmService() {
        return jbpmService;
    }

    public void setJbpmService(JbpmService jbpmService) {
        this.jbpmService = jbpmService;
    }

}

registro-web/src/main/webapp/views/s/adminClientes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

    <ui:composition template="/templates/mainTemplate.xhtml">
        <ui:define name="title">
            DirecTV | Clientes
        </ui:define>

        <ui:define name="content">

            <section>

                <h2 class="text-light text-center">Administrar Clientes</h2>
                <div class="colored-line bg-primary"></div>
                <br/><br/>                


                <h:form id="listClienteForm">
                    <input type="hidden"  name="${_csrf.parameterName}"  value="${_csrf.token}"/>

                    <p:dataTable var="cliente" value="#{adminClientesBean.listCliente}" rows="5"
                                 paginator="true"  reflow="true" editable="false"
                                 sortMode="multiple" widgetVar="clienteTable" 
                                 selectionMode="single" selection="#{adminClientesBean.selectedCliente}" rowKey="#{cliente.cltId}"
                                 paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                 rowsPerPageTemplate="5,10,15" 
                                 class="wow fadeIn" pt:data-wow-delay="0.5s"
                                 >
                        <f:facet name="emptyMessage">
                            <h2 class="text-light">Ningun Cliente</h2>
                        </f:facet>
                        <f:facet name="header">

                            <div class="align-center pos-rel">
                                <span class="fa fa-list-ol" style="position: absolute; left: 5px;font-weight: 300;">&nbsp; #{adminClientesBean.listCliente.size()}</span>
                                Lista de Clientes 
                                <p:inputText id="globalFilter" onkeyup="PF('clienteTable').filter()" class="search-input" placeholder="Buscar"/>
                                <span class="fa fa-search" style="position: absolute; right: 5px;"></span>&nbsp;&nbsp;
                            </div>



                        </f:facet>
                        <p:column headerText="Id" sortBy="#{cliente.cltId}" filterBy="#{cliente.cltId}" filterStyleClass="no-display" filterMatchMode="contains"
                                  width="50">
                            <h:outputText value="#{cliente.cltId}" />
                        </p:column>

                        <p:column width="100" headerText="CI" sortBy="#{cliente.cltCi}" filterBy="#{cliente.cltCi}" filterStyleClass="no-display" filterMatchMode="contains"
                                  >
                            <h:outputText value="#{cliente.cltCi}" />
                        </p:column>

                        <p:column width="150" headerText="Cliente" sortBy="#{cliente.fullName}" filterBy="#{cliente.fullName}" filterStyleClass="no-display" filterMatchMode="contains"
                                  >
                            <h:outputText value="#{cliente.fullName}" />
                        </p:column>
                        <p:column width="100" headerText="Telefono" sortBy="#{cliente.cltTelefono}" filterBy="#{cliente.cltTelefono}" filterStyleClass="no-display" filterMatchMode="contains"
                                  >
                            <h:outputText value="#{cliente.cltTelefono}" />
                        </p:column>
                        <p:column width="170" headerText="Email" sortBy="#{cliente.cltEmail}" filterBy="#{cliente.cltEmail}" filterStyleClass="no-display" filterMatchMode="contains"
                                  >
                            <h:outputText value="#{cliente.cltEmail}" />
                        </p:column>

                        <p:column width="100" headerText="Contrato" sortBy="#{cliente.cltContrato}" filterBy="#{cliente.cltContrato}" filterStyleClass="no-display" filterMatchMode="contains"
                                  >
                            <h:outputText rendered="#{cliente.cltContrato==null or cliente.cltContrato.trim().isEmpty()}" value="no firmado" />
                            <h:outputText rendered="#{not cliente.cltContrato.trim().isEmpty()}"  value="#{cliente.cltContrato}" />
                        </p:column>

                        <p:column width="130" headerText="Estado" sortBy="#{cliente.cltEstado}" filterBy="#{cliente.cltEstado}" filterStyleClass="no-display" filterMatchMode="contains"
                                  >                            
                            <h:outputText value="#{cliente.cltEstado}" />
                        </p:column>
                        <p:column width="80" headerText="Prepago" sortBy="#{cliente.cltIsPrepago}" filterBy="#{cliente.cltIsPrepago}" filterStyleClass="no-display" filterMatchMode="contains"
                                  >

                            <h:outputText value="#{cliente.cltIsPrepago}" />
                        </p:column>


                        <p:column headerText="Acciones" class="align-center" width="150">                                                         

                            <p:commandLink title="Editar"
                                           action="#{adminClientesBean.viewClienteRequestPageAction()}"
                                           class="btn-floating btn-small waves-effect waves-light green">
                                <f:setPropertyActionListener value="#{cliente}" target="#{adminClientesBean.selectedCliente}" />
                                <i class="fa fa-pencil"></i>
                            </p:commandLink> 

                            <p:commandLink title="Subir Contrato"
                                           update="uploadContratoDialogWrap" oncomplete="$('#uploadContratoDialog').modal('show');"
                                           class="btn btn-floating btn-small waves-effect waves-light blue">
                                <f:setPropertyActionListener value="#{cliente}" target="#{adminClientesBean.selectedCliente}" />
                                <i class="fa fa-file-pdf-o"></i>
                            </p:commandLink>                                                         

                        </p:column>
                    </p:dataTable>
                </h:form>




                <h:form id="uploadContratoDialogWrap">
                    <input type="hidden"  name="${_csrf.parameterName}"  value="${_csrf.token}"/>
                    <div class="modal fade" id="uploadContratoDialog" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">

                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Adjuntar Contrato</h4>
                                </div>
                                <div class="modal-body">
                                    <p>Seleccionel el archivo PDF del contrato firmado escaneado.</p>
                                    <p>Esto adjuntará el archivo al proceso.</p>

                                    <h:outputText rendered="#{adminClientesBean.selectedCliente.cltContrato != null and not adminClientesBean.selectedCliente.cltContrato.trim().isEmpty()}"
                                                  value="Subido: #{adminClientesBean.selectedCliente.cltContrato}"/>


                                    <p:fileUpload fileUploadListener="#{adminClientesBean.handleFileUpload}" dragDropSupport="false"
                                                  update="messages2,listClienteForm" sizeLimit="400000" fileLimit="1" allowTypes="/(\.|\/)(pdf)$/" 
                                                  cancelLabel="cancelar" label="Seleccionar PDF" uploadLabel="Subir" 
                                                  oncomplete="$('#uploadContratoDialog').modal('hide');"/>


                                </div>
                                <div class="modal-footer">

                                </div> 

                            </div>

                        </div>
                    </div>
                </h:form>

            </section>
        </ui:define>

    </ui:composition>
</html>

registro-web/src/main/webapp/views/s/estadisticas.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:sec="http://www.springframework.org/security/tags">

    <ui:composition template="/templates/mainTemplate.xhtml">
        <ui:define name="title">
            Estadisticas JOM DCM
        </ui:define>

        <ui:define name="content">

            <section>

                <h1 class="text-light">Estadisticas Portal JOM</h1>
                <br/><br/>
                
                <h:form id="addButtonWrap">
                    <input type="hidden"  name="${_csrf.parameterName}"  value="${_csrf.token}"/>
                    <div class="fixed-action-btn" style="bottom: 55px; right: 24px;">
                        <a class="btn-floating btn-large red">
                            <i class="large fa fa-bars"></i>
                        </a>

                        <ul>                            
                            <li>
                                <p:commandLink class="btn-floating green " title="Atender"
                                               ajax="true" actionListener="#{estadisticasBean.clearJbpmLog}"                                                
                                               style="width:40px;height: 40px;"
                                               >

                                    <i class="fa fa-check-circle Fs20"></i>
                                </p:commandLink>
                            </li>                            
                        </ul>
                    </div>



                    <br/><br/>    
                </h:form>


                <div class="panel panel-primary bd-primary" style="max-width: 700px;margin:auto;">
                    <div class="panel-heading bg-primary">Memoria</div>

                    <div class="panel-body">
                        <p>
                            <h:outputText escape="false" value="#{estadisticasBean.memory}"/>

                        </p>
                        <br/>
                    </div>
                </div>


            </section>
        </ui:define>

    </ui:composition>
</html>